"use client";

import { useStore } from "@/store/useStore";
import { BentoCard } from "@/components/ui/bento-card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Check, X, Zap } from "lucide-react";
import { toast } from "sonner";

export default function OptimizationsPage() {
  const optimizations = useStore(state => state.optimizations);
  const approveOptimization = useStore(state => state.approveOptimization);
  const rejectOptimization = useStore(state => state.rejectOptimization);

  const handleApprove = (id: string) => {
    approveOptimization(id);
    toast.success("Optimization approved and scheduled for execution");
  };

  const handleReject = (id: string) => {
    rejectOptimization(id);
    toast.info("Optimization rejected");
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">AI Optimizations</h1>
        <p className="text-muted-foreground">Actionable recommendations generated by the ML engine.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {optimizations.map(opt => (
          <BentoCard key={opt.id} className={`transition-all ${opt.status !== 'pending' ? 'opacity-70' : ''}`}>
            <div className="flex flex-col h-full">
              <div className="flex justify-between items-start mb-4">
                <div className="flex items-center gap-2">
                  <div className="bg-primary/10 p-2 rounded-full">
                    <Zap className="h-5 w-5 text-primary" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-lg">{opt.type === 'sale' ? 'Promotion Strategy' : opt.type === 'reorder' ? 'Supply Chain' : 'Inventory Transfer'}</h3>
                    <p className="text-sm text-muted-foreground">{opt.id}</p>
                  </div>
                </div>
                <Badge variant={opt.status === 'pending' ? 'outline' : opt.status === 'approved' ? 'default' : 'secondary'}>
                  {opt.status.charAt(0).toUpperCase() + opt.status.slice(1)}
                </Badge>
              </div>
              
              <p className="flex-1 text-lg leading-relaxed mb-6">
                "{opt.message}"
              </p>

              {opt.status === 'pending' && (
                <div className="flex gap-3 mt-auto">
                  <Button 
                    className="flex-1 gap-2" 
                    onClick={() => handleApprove(opt.id)}
                  >
                    <Check className="h-4 w-4" /> Approve
                  </Button>
                  <Button 
                    variant="outline" 
                    className="flex-1 gap-2 text-destructive hover:text-destructive"
                    onClick={() => handleReject(opt.id)}
                  >
                    <X className="h-4 w-4" /> Reject
                  </Button>
                </div>
              )}
            </div>
          </BentoCard>
        ))}
      </div>
    </div>
  );
}
